version: 2

jobs:

  build:

    working_directory: ~/electromagnetics

    docker:

      - image: php:7.2.10-cli-stretch

    steps:

      - checkout

      - run: composer global require --prefer-dist --no-progress --dev squizlabs/php_codesniffer

      - run: composer global require --prefer-dist --no-progress --dev niels-de-blaauw/php-doc-check

      - run: phpcs -p . --standard=Zend,Squiz

      - run: vendor/bin/php-doc-check .

