version: 2

jobs:

  build:

    working_directory: ~/electromagnetics

    docker:

      - image: ayubkhan/edly-wp-plugin:beta

    steps:

      - checkout

      #- run: phpcs -p . --standard=Zend,Squiz

      - run: vendor/bin/php-doc-check .

