version: 2

jobs:

  build:

    working_directory: ~/electromagnetics

    docker:

      - image: edly-wp-plugin:alpha

    steps:

      - checkout
      - run: composer global require --prefer-dist --no-progress --dev squizlabs/php_codesniffer
      - run: composer global require --prefer-dist --no-progress --dev niels-de-blaauw/php-doc-check
      - run: ./../.composer/vendor/bin/phpcs . --standard=Zend,Squiz
      - run: ./../.composer/vendor/bin/php-doc-check .

