version: 2

jobs:

  build:

    working_directory: ~/electromagnetics

    docker:

      - image: ayubkhan/edly-wp-plugin:alpha

    steps:

      - checkout
      - run: ./../.composer/vendor/bin/phpcs . --standard=Zend,Squiz
      - run: ./../.composer/vendor/bin/php-doc-check .

