version: 2

jobs:

  build:

    working_directory: ~/electromagnetics

    docker:

      - image: ayubkhan/edly-wp-plugin:beta

    steps:

      - checkout
      - run: composer global require --prefer-dist --no-progress --dev squizlabs/php_codesniffer
      - run: composer global require --prefer-dist --no-progress --dev niels-de-blaauw/php-doc-check
      - run: pwd
      - run: ./vendor/bin/phpcs . --standard=Zend,Squiz
      - run: ./vendor/bin/php-doc-check .

